pub mod animated_cover;
pub mod artist_info;
pub mod bandcamp;
pub mod favorites;
pub mod goodies;
pub mod http_client;
pub mod layout;
pub mod lyrics;
pub mod playlist_resolver;
pub mod qobuz_downloader;
pub mod rescue;
pub mod songlink;
pub mod soulseek;
pub mod staging;
pub mod tidal;

pub use animated_cover::download_animated_cover;
pub use artist_info::{download_artist_info, download_artist_info_with_url};
pub use favorites::{FavoriteItem, QobuzFavoritesClient};
pub use goodies::download_goodies_booklet;
pub use layout::LibraryLayout;
pub use lyrics::{LyricsClient, LyricsLine, LyricsResponse};
pub use playlist_resolver::PlaylistResolver;
pub use qobuz_downloader::{build_flac_metadata, DownloadRequest, DownloadResult, QobuzDownloader, QobuzTrack};
pub use rescue::{fetch_expected_release_tracklist, rescue_missing_track, MissingTrackInfo};
pub use tidal::{TidalDownloader, TidalTrack};
