//! Regression & Validation Gate Test for MusicBrainz Identifiers [TASK-127]
//!
//! Verifies:
//! 1. Rejection of apocryphal synthetic UUIDv5 MBIDs generated by the legacy
//!    `hydrate_stubs_and_ghosts.py` formula (RFC 4122 DNS namespace + "artist.musicbrainz.org:{name}").
//! 2. Blacklist verification for all known synthetic MBIDs from `mb_artist_cache.json`.
//! 3. Rejection of nil UUIDs, malformed UUIDs, and sentinel strings ("NOT_FOUND", "null", etc.).
//! 4. Acceptance of authentic MusicBrainz UUIDs.
//! 5. Integration with the enrichment pipeline to prevent contamination of `EnrichedMetadata`.

use syncify_metadata_domain::{
    is_valid_musicbrainz_artist_id, is_valid_musicbrainz_id, FieldValidator,
    MusicBrainzValidationError, KNOWN_SYNTHETIC_MBIDS, RFC4122_NAMESPACE_DNS_BYTES,
};
use syncify_tauri_lib::services::enrichment::{EnrichmentEngine, OriginTrackMetadata};

#[test]
fn test_known_synthetic_mbids_from_legacy_cache_are_rejected() {
    assert_eq!(KNOWN_SYNTHETIC_MBIDS.len(), 8);

    for &synthetic_mbid in KNOWN_SYNTHETIC_MBIDS {
        // Must fail the standard validator
        assert!(
            !is_valid_musicbrainz_id(synthetic_mbid),
            "Expected known synthetic MBID {} to be rejected by is_valid_musicbrainz_id",
            synthetic_mbid
        );

        // Must fail FieldValidator check
        assert!(
            !FieldValidator::is_valid_musicbrainz_id(synthetic_mbid),
            "Expected known synthetic MBID {} to be rejected by FieldValidator::is_valid_musicbrainz_id",
            synthetic_mbid
        );

        // Detailed error check
        let err = FieldValidator::validate_musicbrainz_id(synthetic_mbid, None).unwrap_err();
        match err {
            MusicBrainzValidationError::SyntheticApocryphalId(id) => {
                assert_eq!(id, synthetic_mbid);
            }
            other => panic!("Expected SyntheticApocryphalId error variant, got: {:?}", other),
        }
    }
}

#[test]
fn test_synthetic_mbid_generation_matches_python_uuid5_and_is_rejected() {
    // Exact mapping derived from python's uuid.uuid5(uuid.NAMESPACE_DNS, "artist.musicbrainz.org:{name}"):
    let test_cases = [
        ("Alan Mearns", "e774d650-ebf2-5345-acff-8a5ad5cb0ce9"),
        ("Between the Crosses", "505a107a-e964-59e9-98f4-8f55d166ff63"),
        ("Black Door Parole", "32fafb5c-f045-5a3c-a8dd-a0d5bbe136e8"),
        ("Jaade Mx", "4dd9a2f2-8489-500a-a35b-0862f20e2221"),
        ("Karaoke - Tommy James & The Shondells", "fda91c84-f370-544e-8f6d-712491c51f6d"),
        ("Paulo Miranda Silveira", "57843d79-1853-5033-bb05-79713283bfe3"),
        ("Soft Jazz Playlist", "bb5aea5e-ebdb-5181-869c-8d67f9a16a54"),
        ("jade mx", "ff7fe91a-7f2b-5c5a-8e0d-f813e845e2af"),
        // Arbitrary new artists to prove formula parity:
        ("New Ghost Artist 2026", "892f8cea-9b28-5264-b00d-9ab11a8160bb"),
    ];

    for (artist_name, expected_uuid) in test_cases {
        let computed = FieldValidator::compute_synthetic_artist_mbid(artist_name);
        assert_eq!(
            computed, expected_uuid,
            "Calculated UUIDv5 for '{}' must strictly match RFC 4122 / Python uuid5",
            artist_name
        );

        // Verify the synthetic detector detects it
        assert!(
            FieldValidator::is_synthetic_musicbrainz_id(&computed, Some(artist_name)),
            "is_synthetic_musicbrainz_id must detect synthetic MBID for '{}'",
            artist_name
        );

        // Validation gate with artist context must reject it
        assert!(
            !is_valid_musicbrainz_artist_id(&computed, Some(artist_name)),
            "is_valid_musicbrainz_artist_id must reject synthetic MBID for '{}'",
            artist_name
        );

        let err = FieldValidator::validate_musicbrainz_id(&computed, Some(artist_name)).unwrap_err();
        match err {
            MusicBrainzValidationError::SyntheticApocryphalId(id) => {
                assert_eq!(id, computed);
            }
            other => panic!("Expected SyntheticApocryphalId, got {:?}", other),
        }
    }
}

#[test]
fn test_legitimate_musicbrainz_ids_are_accepted() {
    let legit_mbids = [
        // Artists
        ("David Bowie", "5441c29d-3602-4898-b1a1-b77fa23b8e50"),
        ("Pink Floyd", "83d91898-7763-47d7-b03b-b92132375c47"),
        ("Daft Punk", "056e4f3e-d505-4dad-8ec1-d04f521cbb56"),
        ("Anika Noni Rose", "8882d694-77a8-4113-8525-f3436e21ea9f"),
        // Recordings
        ("Heroes (recording)", "b10bbbfc-cf9e-42e0-be17-e2c3e1d2600d"),
        ("Meltdown (recording)", "4029d065-6a1b-4322-a4c5-c406bebb87c1"),
        // Releases
        ("Heroes (release)", "a8d29b20-1d89-425f-bc14-cefb322a36b8"),
        ("Random Access Memories (release)", "3f05c4d0-40e1-4c6e-8219-c09a89eb6e28"),
    ];

    for (desc, legit_id) in legit_mbids {
        assert!(
            is_valid_musicbrainz_id(legit_id),
            "Legitimate MBID for '{}' ({}) should be accepted by is_valid_musicbrainz_id",
            desc,
            legit_id
        );

        assert!(
            FieldValidator::is_valid_musicbrainz_id(legit_id),
            "Legitimate MBID for '{}' ({}) should be accepted by FieldValidator::is_valid_musicbrainz_id",
            desc,
            legit_id
        );

        assert!(
            FieldValidator::validate_musicbrainz_id(legit_id, None).is_ok(),
            "Validation result for '{}' ({}) should be Ok(())",
            desc,
            legit_id
        );
    }
}

#[test]
fn test_sentinels_and_malformed_mbids_are_rejected() {
    let invalid_cases = [
        ("", "Empty string"),
        ("   ", "Whitespace"),
        ("NOT_FOUND", "Sentinel NOT_FOUND uppercase"),
        ("not_found", "Sentinel not_found lowercase"),
        ("null", "String 'null'"),
        ("None", "String 'None'"),
        ("???", "Placeholder '???'"),
        ("N/A", "Placeholder 'N/A'"),
        ("0", "Single digit '0'"),
        ("0000", "Quad zero '0000'"),
        ("00000000-0000-0000-0000-000000000000", "Nil UUID"),
        ("b10bbbfc-cf9e-42e0-be17-e2c3e1d2600", "Truncated (35 chars)"),
        ("b10bbbfc-cf9e-42e0-be17-e2c3e1d2600dd", "Too long (37 chars)"),
        ("b10bbbfc_cf9e_42e0_be17_e2c3e1d2600d", "Underscores instead of hyphens"),
        ("b10bbbfc-cf9e-42e0-be17-e2c3e1d2600g", "Invalid hex character 'g'"),
        ("b10bbbfc-cf9e-42e0-be17-e2c3e1d2600!", "Invalid special char '!'"),
    ];

    for (val, reason) in invalid_cases {
        assert!(
            !is_valid_musicbrainz_id(val),
            "Expected '{}' ({}) to be rejected by is_valid_musicbrainz_id",
            val,
            reason
        );
        assert!(
            !FieldValidator::is_valid_musicbrainz_id(val),
            "Expected '{}' ({}) to be rejected by FieldValidator::is_valid_musicbrainz_id",
            val,
            reason
        );
    }
}

#[test]
fn test_rfc4122_namespace_dns_bytes_invariant() {
    // RFC 4122 DNS namespace: 6ba7b810-9dad-11d1-80b4-00c04fd430c8
    assert_eq!(
        RFC4122_NAMESPACE_DNS_BYTES,
        [0x6b, 0xa7, 0xb8, 0x10, 0x9d, 0xad, 0x11, 0xd1, 0x80, 0xb4, 0x00, 0xc0, 0x4f, 0xd4, 0x30, 0xc8]
    );
}

#[tokio::test]
async fn test_enrichment_pipeline_filters_synthetic_and_invalid_mbids() {
    let engine = EnrichmentEngine::new();

    // 1. Origin metadata containing synthetic MBIDs (as could occur from legacy DB entries)
    let dirty_origin = OriginTrackMetadata {
        title: Some("Song by Alan Mearns".to_string()),
        artist: Some("Alan Mearns".to_string()),
        album: Some("Acoustic Sessions".to_string()),
        // Synthetic MBID for Alan Mearns
        musicbrainz_artist_id: Some("e774d650-ebf2-5345-acff-8a5ad5cb0ce9".to_string()),
        // Sentinel value for recording
        musicbrainz_recording_id: Some("NOT_FOUND".to_string()),
        // Malformed UUID for release
        musicbrainz_release_id: Some("malformed-uuid-value".to_string()),
        ..Default::default()
    };

    // Enrich without external network query
    let enriched = engine
        .resolve_exhaustive_track_metadata(
            "Alan Mearns",
            "Acoustic Sessions",
            "Song by Alan Mearns",
            None,
            &[dirty_origin],
            false, // no external query
        )
        .await;

    // Must NOT accept the synthetic artist ID
    assert_eq!(
        enriched.musicbrainz_artist_id.value(),
        None,
        "Enrichment pipeline must filter out synthetic artist MBID"
    );

    // Must NOT accept the NOT_FOUND recording ID
    assert_eq!(
        enriched.musicbrainz_recording_id.value(),
        None,
        "Enrichment pipeline must filter out NOT_FOUND sentinel"
    );

    // Must NOT accept the malformed release ID
    assert_eq!(
        enriched.musicbrainz_release_id.value(),
        None,
        "Enrichment pipeline must filter out malformed release MBID"
    );
}
