//! Domain contract & deterministic Precedence Engine for Syncify Metadata Enrichment.
//!
//! Shared across backend (`src-tauri`) and CLI (`legacy/syncify-cli`) to guarantee
//! strict parity, identical precedence rules, conflict recording, and safe entity handling.

pub mod country;
pub mod fixtures;
pub mod genre;
pub mod language;

pub use country::*;
pub use genre::*;
pub use language::*;

use serde::{Deserialize, Serialize};
use sha1::{Digest, Sha1};

/// RFC 4122 DNS Namespace UUID bytes (6ba7b810-9dad-11d1-80b4-00c04fd430c8)
pub const RFC4122_NAMESPACE_DNS_BYTES: [u8; 16] = [
    0x6b, 0xa7, 0xb8, 0x10, 0x9d, 0xad, 0x11, 0xd1, 0x80, 0xb4, 0x00, 0xc0, 0x4f, 0xd4, 0x30, 0xc8,
];

/// Known synthetic / apocryphal MBIDs generated by the legacy hydrate_stubs_and_ghosts.py script
/// for ghost artists that returned NOT_FOUND from MusicBrainz.
pub const KNOWN_SYNTHETIC_MBIDS: &[&str] = &[
    "e774d650-ebf2-5345-acff-8a5ad5cb0ce9", // Alan Mearns
    "505a107a-e964-59e9-98f4-8f55d166ff63", // Between the Crosses
    "32fafb5c-f045-5a3c-a8dd-a0d5bbe136e8", // Black Door Parole
    "4dd9a2f2-8489-500a-a35b-0862f20e2221", // Jaade Mx
    "fda91c84-f370-544e-8f6d-712491c51f6d", // Karaoke - Tommy James & The Shondells
    "57843d79-1853-5033-bb05-79713283bfe3", // Paulo Miranda Silveira
    "bb5aea5e-ebdb-5181-869c-8d67f9a16a54", // Soft Jazz Playlist
    "ff7fe91a-7f2b-5c5a-8e0d-f813e845e2af", // jade mx
];

/// Reason why a MusicBrainz ID was rejected by the validation gate.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum MusicBrainzValidationError {
    EmptyOrWhitespace,
    SentinelValue(String),
    MalformedUuid(String),
    NilUuid,
    SyntheticApocryphalId(String),
}

impl std::fmt::Display for MusicBrainzValidationError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::EmptyOrWhitespace => write!(f, "MusicBrainz ID is empty or whitespace"),
            Self::SentinelValue(s) => write!(f, "MusicBrainz ID is a placeholder/sentinel value: '{}'", s),
            Self::MalformedUuid(s) => write!(f, "MusicBrainz ID is not a valid 36-char canonical UUID: '{}'", s),
            Self::NilUuid => write!(f, "MusicBrainz ID is nil UUID (00000000-0000-0000-0000-000000000000)"),
            Self::SyntheticApocryphalId(s) => write!(f, "MusicBrainz ID is an apocryphal/synthetic UUIDv5: '{}'", s),
        }
    }
}

impl std::error::Error for MusicBrainzValidationError {}

/// Source priority tiers (Rank 5 is highest)
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum SourcePriority {
    /// Inferred or heuristic fallback (e.g. filename parser, rule engine, local DSP analysis)
    Inferred = 1,
    /// Spotify metadata
    SpotifyMetadata = 2,
    /// MusicBrainz open database
    MusicBrainz = 3,
    /// Streaming service origin metadata (Qobuz, Tidal, Apple Music, Deezer)
    StreamingService = 4,
    /// User manual input or explicit override
    Manual = 5,
}

impl SourcePriority {
    pub fn from_source_name(source: &str) -> Self {
        match source.to_lowercase().as_str() {
            "manual" | "user" | "user_override" => SourcePriority::Manual,
            "qobuz" | "tidal" | "deezer" | "apple_music" | "stream" | "origin" | "input" | "streaming" | "streamingservice" => {
                SourcePriority::StreamingService
            }
            "musicbrainz" | "mb" => SourcePriority::MusicBrainz,
            "spotify" | "spotify_metadata" | "spotifymetadata" => SourcePriority::SpotifyMetadata,
            _ => SourcePriority::Inferred,
        }
    }
}

/// Explicit resolution states for enrichment fields
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "status", rename_all = "snake_case")]
pub enum FieldResolution {
    Resolved {
        value: String,
        source: String,
        confidence: f64,
        resolved_at: String,
        conflict: Option<ConflictInfo>,
    },
    NotFound {
        source: String,
        checked_at: String,
    },
    NotSupported {
        reason: String,
    },
    SourceUnavailable {
        source: String,
        error: String,
    },
    Failed {
        source: String,
        error: String,
        failed_at: String,
    },
    NotRequested,
}

impl Default for FieldResolution {
    fn default() -> Self {
        FieldResolution::NotRequested
    }
}

/// Information registered when two valid enrichment sources conflict
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ConflictInfo {
    pub alternate_source: String,
    pub alternate_value: String,
    pub alternate_confidence: f64,
    pub conflict_reason: String,
}

/// Field-specific validator avoiding naive global blacklists while rejecting invalid placeholders
pub struct FieldValidator;

const KNOWN_TECHNICAL_ROLE_PREFIXES: &[&str] = &[
    "guitar", "electric guitar", "acoustic guitar", "classical guitar", "lead guitar", "rhythm guitar",
    "bass", "bass guitar", "acoustic bass", "double bass", "contrabass",
    "drums", "drum", "percussion", "timpani", "cymbals", "snare", "tambourine", "congas", "bongos",
    "vocals", "vocal", "lead vocals", "backing vocals", "background vocals", "voice", "singer", "soloist",
    "choir", "chorus",
    "piano", "keyboards", "keyboard", "organ", "synthesizer", "synth", "clavinet", "harpsichord", "accordion",
    "violin", "viola", "cello", "violoncello", "strings", "harp", "fiddle", "banjo", "mandolin", "ukulele",
    "trumpet", "trombone", "tuba", "french horn", "horn", "horns", "brass", "flugelhorn",
    "saxophone", "sax", "alto saxophone", "tenor saxophone", "baritone saxophone", "soprano saxophone",
    "flute", "clarinet", "oboe", "bassoon", "woodwinds", "harmonica",
    "producer", "co-producer", "executive producer", "associate producer", "additional producer",
    "composer", "songwriter", "writer", "lyricist", "arranger", "conductor", "director",
    "mixer", "mixing", "mixing engineer", "sound engineer", "audio engineer", "recording engineer",
    "engineer", "mastering engineer", "mastering", "remastering", "editing engineer", "programmer", "programming", "dj",
];

/// Checks if an artist string starts with a recognized technical role prefix like "Guitar - ...", "Producer - ..."
pub fn has_technical_role_prefix(val: &str) -> bool {
    let t = val.trim();
    if t.is_empty() {
        return false;
    }
    let lower = t.to_lowercase();
    for prefix in KNOWN_TECHNICAL_ROLE_PREFIXES {
        let p_len = prefix.len();
        if lower.starts_with(prefix) {
            let rest = &t[p_len..];
            if rest.starts_with(" - ") || rest.starts_with(" – ") || rest.starts_with(" — ") || rest.starts_with(": ") || rest.starts_with(", ") {
                let after = rest[3..].trim();
                if !after.is_empty() {
                    return true;
                }
            } else if rest.starts_with(':') {
                let after = rest[1..].trim();
                if !after.is_empty() {
                    return true;
                }
            }
        }
    }
    false
}

impl FieldValidator {
    /// Validate track/album title: whitespace-only and synthetic '???' rejected.
    /// Genuine titles like 'Untitled' or 'Unknown' (if literal track name) are allowed unless pure placeholder.
    pub fn is_valid_title(val: &str) -> bool {
        let t = val.trim();
        !t.is_empty() && t != "???" && t != "null" && t != "None"
    }

    /// Validate artist name: whitespace-only, strings with unparsed linebreaks, and technical role prefixes rejected.
    /// 'Various Artists' and 'Various' are strictly VALID for compilation albums.
    pub fn is_valid_artist(val: &str) -> bool {
        let t = val.trim();
        if t.is_empty() || t == "???" || t == "null" || t == "None" || t.contains('\r') || t.contains('\n') {
            return false;
        }
        if has_technical_role_prefix(t) {
            return false;
        }
        true
    }

    /// Validate year / date: '0000', '0', empty rejected.
    pub fn is_valid_year(val: &str) -> bool {
        let t = val.trim();
        if t.is_empty() || t == "0000" || t == "0" || t == "null" || t == "None" {
            return false;
        }
        t.chars().any(|c| c.is_ascii_digit())
    }

    /// Validate identifier (ISRC, UPC, MBID): empty, '0', 'null', 'None' rejected.
    pub fn is_valid_identifier(val: &str) -> bool {
        let t = val.trim();
        !t.is_empty() && t != "0" && t != "0000" && t != "null" && t != "None" && t != "???" && t != "N/A"
    }

    /// Validate label / organization: whitespace-only, generic 'N/A' rejected.
    pub fn is_valid_label(val: &str) -> bool {
        let t = val.trim();
        !t.is_empty() && !t.eq_ignore_ascii_case("n/a") && t != "null" && t != "None" && t != "???"
    }

    /// Validate genre / style / mood
    pub fn is_valid_genre(val: &str) -> bool {
        genre::is_valid_genre(val)
    }

    /// Validate genre / style / mood within track context (rejection of matching title/artist/album/label)
    pub fn is_valid_genre_with_context(val: &str, context: Option<&GenreContext>) -> bool {
        genre::is_valid_genre_with_context(val, context)
    }

    /// Validate language code (ISO 639-1 / 639-2)
    pub fn is_valid_language(val: &str) -> bool {
        let t = val.trim();
        !t.is_empty() && (t.len() == 2 || t.len() == 3) && t.chars().all(|c| c.is_ascii_alphabetic())
    }

    /// Validate ISO 3166-1 country code
    pub fn is_valid_country(val: &str) -> bool {
        let t = val.trim();
        !t.is_empty() && (t.len() == 2 || t.len() == 3) && t.chars().all(|c| c.is_ascii_alphabetic())
    }

    /// Validate BPM
    pub fn is_valid_bpm(val: u32) -> bool {
        val > 0 && val < 500
    }

    /// Validate musical key
    pub fn is_valid_key(val: &str) -> bool {
        let t = val.trim();
        !t.is_empty() && !t.eq_ignore_ascii_case("unknown") && t != "null" && t != "None" && t != "???"
    }

    /// Validate AcoustID ID (UUID / hex format)
    pub fn is_valid_acoustid(val: &str) -> bool {
        let t = val.trim();
        !t.is_empty()
            && t != "0"
            && t != "null"
            && t != "None"
            && t != "???"
            && t != "N/A"
            && t.chars().all(|c| c.is_ascii_hexdigit() || c == '-')
    }

    /// Validate ReplayGain / EBU R128 gain string
    pub fn is_valid_gain(val: &str) -> bool {
        let t = val.trim();
        !t.is_empty() && !t.eq_ignore_ascii_case("unknown") && t != "null" && t != "None" && t != "???"
    }

    /// Check if a string is a syntactically valid canonical UUID (36 chars: 8-4-4-4-12 hex).
    pub fn is_canonical_uuid(val: &str) -> bool {
        let b = val.trim().as_bytes();
        if b.len() != 36 {
            return false;
        }
        for (i, &byte) in b.iter().enumerate() {
            if i == 8 || i == 13 || i == 18 || i == 23 {
                if byte != b'-' {
                    return false;
                }
            } else if !byte.is_ascii_hexdigit() {
                return false;
            }
        }
        true
    }

    /// Compute the apocryphal synthetic UUIDv5 generated by the legacy
    /// `hydrate_stubs_and_ghosts.py` formula:
    /// `uuid.uuid5(uuid.NAMESPACE_DNS, f"artist.musicbrainz.org:{artist_name.strip()}")`
    pub fn compute_synthetic_artist_mbid(artist_name: &str) -> String {
        let clean = artist_name.trim();
        let name_str = format!("artist.musicbrainz.org:{}", clean);
        let mut hasher = Sha1::new();
        hasher.update(&RFC4122_NAMESPACE_DNS_BYTES);
        hasher.update(name_str.as_bytes());
        let digest = hasher.finalize();

        let mut bytes = [0u8; 16];
        bytes.copy_from_slice(&digest[0..16]);
        // Set version to 5 (0101 in upper 4 bits)
        bytes[6] = (bytes[6] & 0x0f) | 0x50;
        // Set variant to RFC 4122 (10xx in upper 2 bits)
        bytes[8] = (bytes[8] & 0x3f) | 0x80;

        format!(
            "{:02x}{:02x}{:02x}{:02x}-{:02x}{:02x}-{:02x}{:02x}-{:02x}{:02x}-{:02x}{:02x}{:02x}{:02x}{:02x}{:02x}",
            bytes[0], bytes[1], bytes[2], bytes[3],
            bytes[4], bytes[5],
            bytes[6], bytes[7],
            bytes[8], bytes[9],
            bytes[10], bytes[11], bytes[12], bytes[13], bytes[14], bytes[15]
        )
    }

    /// Returns true if the MBID matches any known synthetic MBID or matches
    /// the UUIDv5 synthetic generator for the given artist name.
    pub fn is_synthetic_musicbrainz_id(mbid: &str, artist_name: Option<&str>) -> bool {
        let mbid_clean = mbid.trim().to_ascii_lowercase();
        if KNOWN_SYNTHETIC_MBIDS.iter().any(|k| mbid_clean == *k) {
            return true;
        }
        if let Some(art) = artist_name {
            let art_clean = art.trim();
            if !art_clean.is_empty() {
                let synthetic = Self::compute_synthetic_artist_mbid(art_clean);
                if mbid_clean == synthetic {
                    return true;
                }
            }
        }
        false
    }

    /// Validate MusicBrainz ID syntax, nil rejection, sentinel rejection,
    /// and known apocryphal synthetic UUID blacklist.
    pub fn is_valid_musicbrainz_id(mbid: &str) -> bool {
        Self::validate_musicbrainz_id(mbid, None).is_ok()
    }

    /// Validate MusicBrainz Artist ID including the specific artist context
    /// to reject synthetic UUIDv5 IDs generated for that specific artist.
    pub fn is_valid_musicbrainz_artist_id(mbid: &str, artist_name: Option<&str>) -> bool {
        Self::validate_musicbrainz_id(mbid, artist_name).is_ok()
    }

    /// Detailed validation gate returning specific reason for rejection.
    pub fn validate_musicbrainz_id(
        mbid: &str,
        artist_name: Option<&str>,
    ) -> Result<(), MusicBrainzValidationError> {
        let t = mbid.trim();
        if t.is_empty() {
            return Err(MusicBrainzValidationError::EmptyOrWhitespace);
        }

        // Sentinel / placeholder checks
        if t.eq_ignore_ascii_case("not_found")
            || t.eq_ignore_ascii_case("null")
            || t.eq_ignore_ascii_case("none")
            || t.eq_ignore_ascii_case("undefined")
            || t.eq_ignore_ascii_case("unknown")
            || t == "???"
            || t == "N/A"
            || t == "0"
            || t == "0000"
        {
            return Err(MusicBrainzValidationError::SentinelValue(t.to_string()));
        }

        // Canonical UUID check (36 chars: 8-4-4-4-12 hex)
        if !Self::is_canonical_uuid(t) {
            return Err(MusicBrainzValidationError::MalformedUuid(t.to_string()));
        }

        // Nil UUID check
        if t == "00000000-0000-0000-0000-000000000000" {
            return Err(MusicBrainzValidationError::NilUuid);
        }

        // Synthetic apocryphal check
        if Self::is_synthetic_musicbrainz_id(t, artist_name) {
            return Err(MusicBrainzValidationError::SyntheticApocryphalId(t.to_string()));
        }

        Ok(())
    }
}

/// Convenient top-level gate to check if a MusicBrainz ID is valid.
pub fn is_valid_musicbrainz_id(mbid: &str) -> bool {
    FieldValidator::is_valid_musicbrainz_id(mbid)
}

/// Convenient top-level gate to check if a MusicBrainz Artist ID is valid
/// and not an apocryphal synthetic UUID generated for that artist.
pub fn is_valid_musicbrainz_artist_id(mbid: &str, artist_name: Option<&str>) -> bool {
    FieldValidator::is_valid_musicbrainz_artist_id(mbid, artist_name)
}

impl FieldResolution {
    pub fn value(&self) -> Option<&str> {
        match self {
            FieldResolution::Resolved { value, .. } => Some(value.as_str()),
            _ => None,
        }
    }

    pub fn source(&self) -> Option<&str> {
        match self {
            FieldResolution::Resolved { source, .. } => Some(source.as_str()),
            FieldResolution::NotFound { source, .. } => Some(source.as_str()),
            FieldResolution::SourceUnavailable { source, .. } => Some(source.as_str()),
            FieldResolution::Failed { source, .. } => Some(source.as_str()),
            _ => None,
        }
    }

    pub fn confidence(&self) -> f64 {
        match self {
            FieldResolution::Resolved { confidence, .. } => *confidence,
            _ => 0.0,
        }
    }

    pub fn is_resolved(&self) -> bool {
        matches!(self, FieldResolution::Resolved { .. })
    }

    /// Merge candidate applying the strict Precedence Policy:
    /// 1. Manual source is immutable (unless force is true).
    /// 2. Higher SourcePriority wins.
    /// 3. If SourcePriority is equal, higher confidence wins.
    /// 4. If values conflict, log ConflictInfo without concealing it.
    pub fn merge_candidate(
        &mut self,
        new_val: Option<String>,
        source: &str,
        confidence: f64,
        now_ts: &str,
    ) {
        self.merge_candidate_with_force(new_val, source, confidence, now_ts, false);
    }

    /// Merge candidate with optional force flag to override higher precedence values
    pub fn merge_candidate_with_force(
        &mut self,
        new_val: Option<String>,
        source: &str,
        confidence: f64,
        now_ts: &str,
        force: bool,
    ) {
        let clean_val = match new_val {
            Some(ref s) if !s.trim().is_empty() => s.trim().to_string(),
            _ => return,
        };

        let new_prio = SourcePriority::from_source_name(source);

        match self {
            FieldResolution::Resolved {
                ref mut value,
                source: ref mut curr_src,
                confidence: ref mut curr_conf,
                ref mut resolved_at,
                ref mut conflict,
            } => {
                let curr_prio = SourcePriority::from_source_name(curr_src);

                // Manual source is unconditionally preserved unless forced
                if curr_prio == SourcePriority::Manual && !force {
                    return;
                }

                // If identical value, retain and update confidence if higher
                if value == &clean_val {
                    if force || new_prio > curr_prio || (new_prio == curr_prio && confidence > *curr_conf) {
                        *curr_src = source.to_string();
                        *curr_conf = confidence;
                        *resolved_at = now_ts.to_string();
                    }
                    return;
                }

                // Conflicting values: compare priority first, then confidence (or force)
                if force || new_prio > curr_prio || (new_prio == curr_prio && confidence > *curr_conf) {
                    *conflict = Some(ConflictInfo {
                        alternate_source: curr_src.clone(),
                        alternate_value: value.clone(),
                        alternate_confidence: *curr_conf,
                        conflict_reason: format!(
                            "Replaced by {}candidate from {} (prio: {:?}, conf: {:.2})",
                            if force { "force-overridden " } else { "higher-priority " },
                            source, new_prio, confidence
                        ),
                    });
                    *value = clean_val;
                    *curr_src = source.to_string();
                    *curr_conf = confidence;
                    *resolved_at = now_ts.to_string();
                } else {
                    if conflict.is_none() {
                        *conflict = Some(ConflictInfo {
                            alternate_source: source.to_string(),
                            alternate_value: clean_val,
                            alternate_confidence: confidence,
                            conflict_reason: format!(
                                "Lower priority candidate from {} rejected in favor of {}",
                                source, curr_src
                            ),
                        });
                    }
                }
            }
            _ => {
                *self = FieldResolution::Resolved {
                    value: clean_val,
                    source: source.to_string(),
                    confidence,
                    resolved_at: now_ts.to_string(),
                    conflict: None,
                };
            }
        }
    }
}



/// Fuses language candidates from multiple providers:
/// - Normalizes to ISO 639-2 (3-letter lowercase)
/// - Resolves conflicts using strict source precedence (Manual > StreamingService > MusicBrainz > SpotifyMetadata > Inferred)
///   or majority/confidence among equal priority
/// - Never leaves empty if at least one valid language is supplied
pub fn fuse_languages(lang_inputs: &[(&str, &str, f64)]) -> Option<String> {
    let mut resolved_candidates: Vec<(String, SourcePriority, f64)> = Vec::new();

    for (val, source, conf) in lang_inputs {
        if let Some(norm_lang) = resolve_language(val) {
            let prio = SourcePriority::from_source_name(source);
            resolved_candidates.push((norm_lang, prio, *conf));
        }
    }

    if resolved_candidates.is_empty() {
        return None;
    }

    // Sort by Priority desc, then confidence desc
    resolved_candidates.sort_by(|a, b| {
        b.1.cmp(&a.1).then_with(|| b.2.partial_cmp(&a.2).unwrap_or(std::cmp::Ordering::Equal))
    });

    let highest_prio = resolved_candidates[0].1;
    let top_tier: Vec<_> = resolved_candidates.iter().filter(|c| c.1 == highest_prio).collect();

    // If multiple candidates in top tier, find majority or highest confidence
    let mut counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for c in &top_tier {
        *counts.entry(&c.0).or_insert(0) += 1;
    }

    top_tier.iter()
        .max_by(|a, b| {
            let count_a = counts.get(a.0.as_str()).unwrap_or(&0);
            let count_b = counts.get(b.0.as_str()).unwrap_or(&0);
            count_a.cmp(count_b).then_with(|| a.2.partial_cmp(&b.2).unwrap_or(std::cmp::Ordering::Equal))
        })
        .map(|c| c.0.clone())
}

/// Fuses country candidates from multiple providers:
/// - Normalizes to real English country name (e.g. "United States", "Germany", "United Kingdom", "Japan")
/// - Resolves conflicts by prioritizing official release streaming provider (Qobuz/Tidal) or MusicBrainz
pub fn fuse_countries(country_inputs: &[(&str, &str, f64)]) -> Option<String> {
    let mut candidates: Vec<(String, SourcePriority, f64)> = Vec::new();

    for (val, source, conf) in country_inputs {
        let trimmed = val.trim();
        if trimmed.is_empty() {
            continue;
        }

        let canonical = match resolve_country(trimmed) {
            CountryResolution::Country { canonical_name, .. } => Some(canonical_name),
            CountryResolution::Region { .. } => None,
            CountryResolution::Unknown(_) => {
                if trimmed.len() == 2 && trimmed.chars().all(|c| c.is_ascii_alphabetic()) {
                    tracing::warn!("Unrecognized country code rejected: '{}'", trimmed);
                    None
                } else if trimmed.len() >= 4 {
                    Some(trimmed.to_string())
                } else {
                    None
                }
            }
        };

        if let Some(c_name) = canonical {
            let prio = SourcePriority::from_source_name(source);
            candidates.push((c_name, prio, *conf));
        }
    }

    if candidates.is_empty() {
        return None;
    }

    candidates.sort_by(|a, b| {
        b.1.cmp(&a.1).then_with(|| b.2.partial_cmp(&a.2).unwrap_or(std::cmp::Ordering::Equal))
    });

    Some(candidates[0].0.clone())
}

/// Fuses multiple label strings / variants across providers
pub fn fuse_labels(label_inputs: &[&str]) -> Vec<String> {
    let mut unique_labels: Vec<String> = Vec::new();

    for input in label_inputs {
        let trimmed = input.trim();
        if FieldValidator::is_valid_label(trimmed) {
            // Split by ';' if composite
            for token in trimmed.split(';') {
                let t = token.trim();
                if FieldValidator::is_valid_label(t) && !unique_labels.iter().any(|l| l.eq_ignore_ascii_case(t)) {
                    unique_labels.push(t.to_string());
                }
            }
        }
    }

    unique_labels
}

/// Enriched Metadata DTO for all metadata domains with provenance & precedence tracking
#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq)]
pub struct EnrichedMetadata {
    // 1. Title, Artist & Core Structure
    pub title: FieldResolution,
    pub artist: FieldResolution,
    pub album: FieldResolution,
    pub album_artist: FieldResolution,
    pub composer: FieldResolution,
    pub performers: FieldResolution,
    pub work: FieldResolution,
    pub track_number: FieldResolution,
    pub track_total: FieldResolution,
    pub disc_number: FieldResolution,
    pub disc_total: FieldResolution,
    pub disc_subtitle: FieldResolution,

    // 2. Release & Editorial Details
    pub release_year: FieldResolution,
    pub release_date: FieldResolution,
    pub original_date: FieldResolution,
    pub label: FieldResolution,
    pub catalog_number: FieldResolution,
    pub copyright: FieldResolution,
    pub release_type: FieldResolution,
    pub release_status: FieldResolution,
    pub release_country: FieldResolution,
    pub release_region: FieldResolution,
    pub language: FieldResolution,
    pub compilation: FieldResolution,
    pub grouping: FieldResolution,
    pub media_type: FieldResolution,

    // 3. Acoustic & Musical Properties
    pub genre: FieldResolution,
    pub style: FieldResolution,
    pub mood: FieldResolution,
    pub tags: FieldResolution,
    pub artist_tags: FieldResolution,
    pub explicit: FieldResolution,
    pub bpm: FieldResolution,
    pub initial_key: FieldResolution,
    pub energy: FieldResolution,
    pub danceability: FieldResolution,
    pub loudness: FieldResolution,
    pub replaygain_track_gain: FieldResolution,
    pub replaygain_track_peak: FieldResolution,
    pub replaygain_album_gain: FieldResolution,
    pub replaygain_album_peak: FieldResolution,
    pub r128_track_gain: FieldResolution,
    pub comment: FieldResolution,

    // 4. Industry Identifiers & Provenance
    pub isrc: FieldResolution,
    pub barcode: FieldResolution,
    pub acoustid_id: FieldResolution,
    pub acoustid_fingerprint: FieldResolution,
    pub lyrics_source: FieldResolution,
    pub cover_source: FieldResolution,
    pub audio_source: FieldResolution,

    // 5. MusicBrainz MBIDs
    pub musicbrainz_recording_id: FieldResolution,
    pub musicbrainz_release_id: FieldResolution,
    pub musicbrainz_release_group_id: FieldResolution,
    pub musicbrainz_artist_id: FieldResolution,
    pub musicbrainz_albumartist_id: FieldResolution,
    pub musicbrainz_work_id: FieldResolution,

    pub enriched_at: String,
}

/// Audio analysis metrics extracted from physical audio stream / staging file
#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq)]
pub struct AudioAnalysisMetrics {
    pub bpm: Option<u32>,
    pub initial_key: Option<String>,
    pub energy: Option<f64>,
    pub danceability: Option<f64>,
    pub loudness: Option<f64>,
    pub replaygain_track_gain: Option<String>,
    pub replaygain_track_peak: Option<String>,
    pub replaygain_album_gain: Option<String>,
    pub replaygain_album_peak: Option<String>,
    pub r128_track_gain: Option<String>,
    pub acoustid_id: Option<String>,
    pub acoustid_fingerprint: Option<String>,
    pub duration_sec: Option<f64>,
}

impl EnrichedMetadata {
    /// Apply audio analysis metrics (ReplayGain, Acoustic Features, AcoustID Fingerprint)
    /// following strict precedence rules (Inferred source).
    pub fn apply_audio_analysis(
        &mut self,
        analysis: &AudioAnalysisMetrics,
        source: &str,
        now_ts: &str,
    ) {
        if let Some(bpm_val) = analysis.bpm {
            if FieldValidator::is_valid_bpm(bpm_val) {
                self.bpm.merge_candidate(Some(bpm_val.to_string()), source, 0.85, now_ts);
            }
        }
        if let Some(ref key_val) = analysis.initial_key {
            if FieldValidator::is_valid_key(key_val) {
                self.initial_key.merge_candidate(Some(key_val.clone()), source, 0.85, now_ts);
            }
        }
        if let Some(en) = analysis.energy {
            self.energy.merge_candidate(Some(format!("{:.2}", en)), source, 0.85, now_ts);
        }
        if let Some(da) = analysis.danceability {
            self.danceability.merge_candidate(Some(format!("{:.2}", da)), source, 0.85, now_ts);
        }
        if let Some(lo) = analysis.loudness {
            self.loudness.merge_candidate(Some(format!("{:.1}", lo)), source, 0.85, now_ts);
        }
        if let Some(ref rtg) = analysis.replaygain_track_gain {
            if FieldValidator::is_valid_gain(rtg) {
                self.replaygain_track_gain.merge_candidate(Some(rtg.clone()), source, 0.85, now_ts);
            }
        }
        if let Some(ref rtp) = analysis.replaygain_track_peak {
            if FieldValidator::is_valid_gain(rtp) {
                self.replaygain_track_peak.merge_candidate(Some(rtp.clone()), source, 0.85, now_ts);
            }
        }
        if let Some(ref rag) = analysis.replaygain_album_gain {
            if FieldValidator::is_valid_gain(rag) {
                self.replaygain_album_gain.merge_candidate(Some(rag.clone()), source, 0.85, now_ts);
            }
        }
        if let Some(ref rap) = analysis.replaygain_album_peak {
            if FieldValidator::is_valid_gain(rap) {
                self.replaygain_album_peak.merge_candidate(Some(rap.clone()), source, 0.85, now_ts);
            }
        }
        if let Some(ref r128) = analysis.r128_track_gain {
            if FieldValidator::is_valid_gain(r128) {
                self.r128_track_gain.merge_candidate(Some(r128.clone()), source, 0.85, now_ts);
            }
        }
        if let Some(ref aid) = analysis.acoustid_id {
            if FieldValidator::is_valid_acoustid(aid) {
                self.acoustid_id.merge_candidate(Some(aid.clone()), source, 0.90, now_ts);
            }
        }
        if let Some(ref fp) = analysis.acoustid_fingerprint {
            if !fp.trim().is_empty() {
                self.acoustid_fingerprint.merge_candidate(Some(fp.clone()), source, 0.90, now_ts);
            }
        }
    }

    /// Evaluates the metadata enrichment completeness level
    pub fn completeness(&self) -> EnrichmentCompleteness {
        let has_core = self.title.value().is_some()
            && self.artist.value().is_some()
            && self.album.value().is_some();
        let has_ids = self.isrc.value().is_some()
            || self.musicbrainz_recording_id.value().is_some()
            || self.musicbrainz_release_id.value().is_some();
        let has_extended = self.track_number.value().is_some()
            || self.release_date.value().is_some()
            || self.release_year.value().is_some()
            || self.label.value().is_some()
            || self.genre.value().is_some()
            || self.composer.value().is_some();

        if has_core && has_ids && has_extended {
            EnrichmentCompleteness::Enriched
        } else if has_core || has_ids {
            EnrichmentCompleteness::Partial
        } else {
            EnrichmentCompleteness::Minimal
        }
    }
}

/// Completeness rating for enriched metadata records
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum EnrichmentCompleteness {
    Enriched,
    Partial,
    Minimal,
}

pub fn normalize_title(title: &str) -> String {
    title
        .to_lowercase()
        .chars()
        .filter(|c| c.is_alphanumeric() || c.is_whitespace())
        .collect::<String>()
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
}

pub fn chrono_now_iso() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let dur = SystemTime::now().duration_since(UNIX_EPOCH).unwrap();
    format!("{}.{:03}Z", dur.as_secs(), dur.subsec_millis())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::fixtures::*;

    #[test]
    fn test_manual_source_is_immutable_against_higher_confidence() {
        let mut field = FieldResolution::default();
        let now = chrono_now_iso();
        field.merge_candidate(Some("Manual Title".to_string()), "manual", 1.0, &now);

        // Attempt overwrite with MusicBrainz higher confidence
        field.merge_candidate(Some("MB Title".to_string()), "musicbrainz", 0.99, &now);

        assert_eq!(field.value(), Some("Manual Title"));
        assert_eq!(field.source(), Some("manual"));
        assert_eq!(field.confidence(), 1.0);
    }

    #[test]
    fn test_source_priority_streaming_over_musicbrainz() {
        let mut field = FieldResolution::default();
        let now = chrono_now_iso();
        // MusicBrainz candidate first
        field.merge_candidate(Some("MB Album".to_string()), "musicbrainz", 0.95, &now);
        assert_eq!(field.value(), Some("MB Album"));

        // Streaming candidate (higher priority) arrives
        field.merge_candidate(Some("Official Stream Album".to_string()), "qobuz", 0.90, &now);
        assert_eq!(field.value(), Some("Official Stream Album"));
        assert_eq!(field.source(), Some("qobuz"));

        if let FieldResolution::Resolved { ref conflict, .. } = field {
            assert!(conflict.is_some());
            let c = conflict.as_ref().unwrap();
            assert_eq!(c.alternate_source, "musicbrainz");
            assert_eq!(c.alternate_value, "MB Album");
        } else {
            panic!("Expected Resolved variant");
        }
    }

    #[test]
    fn test_placeholder_validation_rules() {
        assert!(!FieldValidator::is_valid_year("0000"));
        assert!(!FieldValidator::is_valid_year("0"));
        assert!(!FieldValidator::is_valid_year(""));
        assert!(FieldValidator::is_valid_year("1977"));

        assert!(!FieldValidator::is_valid_identifier(""));
        assert!(!FieldValidator::is_valid_identifier("null"));
        assert!(!FieldValidator::is_valid_identifier("None"));
        assert!(FieldValidator::is_valid_identifier("USRC12345678"));
        assert!(FieldValidator::is_valid_identifier("0035629007421"));

        // 'Various Artists' is VALID for compilations
        assert!(FieldValidator::is_valid_artist("Various Artists"));
        assert!(FieldValidator::is_valid_artist("Various"));
        assert!(!FieldValidator::is_valid_artist("???"));
        assert!(!FieldValidator::is_valid_artist("   "));

        // TASK-68: Reject technical role prefixes
        assert!(!FieldValidator::is_valid_artist("Guitar - Juan Perez"));
        assert!(!FieldValidator::is_valid_artist("Choir - Coro de Praga"));
        assert!(!FieldValidator::is_valid_artist("Composer - Beethoven"));
        assert!(!FieldValidator::is_valid_artist("Producer - Quincy Jones"));
        assert!(!FieldValidator::is_valid_artist("Vocals - John Doe"));
        assert!(FieldValidator::is_valid_artist("Guitar Wolf"));
        assert!(FieldValidator::is_valid_artist("Jean-Luc Ponty"));
    }

    #[test]
    fn test_musicbrainz_exact_match_fixture_parsing() {
        let json_val: serde_json::Value = serde_json::from_str(FIXTURE_MB_EXACT_RECORDING_JSON).unwrap();
        assert_eq!(json_val["id"].as_str(), Some("b10bbbfc-cf9e-42e0-be17-e2c3e1d2600d"));
        assert_eq!(json_val["title"].as_str(), Some("Heroes"));
        let releases = json_val["releases"].as_array().unwrap();
        assert_eq!(releases.len(), 1);
        assert_eq!(releases[0]["date"].as_str(), Some("1977-10-14"));
        assert_eq!(releases[0]["label-info"][0]["label"]["name"].as_str(), Some("RCA Victor"));
    }

    #[test]
    fn test_musicbrainz_alternative_release_selection() {
        let json_val: serde_json::Value = serde_json::from_str(FIXTURE_MB_ALTERNATIVE_RELEASE_JSON).unwrap();
        let releases = json_val["releases"].as_array().unwrap();

        let norm_album = normalize_title("Heroes");
        let matched_rel = releases.iter().find(|r| {
            let t = normalize_title(r["title"].as_str().unwrap_or(""));
            t == norm_album
        });

        assert!(matched_rel.is_some());
        let rel = matched_rel.unwrap();
        assert_eq!(rel["id"].as_str(), Some("673752e3-2e06-4447-aa72-a080ef8a1768"));
        assert_eq!(rel["date"].as_str(), Some("1977-10-14"));
    }

    #[test]
    fn test_full_source_hierarchy_precedence() {
        let mut field = FieldResolution::default();
        let now = chrono_now_iso();

        // 1. Inferred arrives first
        field.merge_candidate(Some("Inferred Genre".to_string()), "inferred", 0.50, &now);
        assert_eq!(field.value(), Some("Inferred Genre"));

        // 2. MusicBrainz beats Inferred
        field.merge_candidate(Some("MB Art Rock".to_string()), "musicbrainz", 0.80, &now);
        assert_eq!(field.value(), Some("MB Art Rock"));
        assert_eq!(field.source(), Some("musicbrainz"));

        // 3. StreamingService beats MusicBrainz
        field.merge_candidate(Some("Glam Rock".to_string()), "qobuz", 0.90, &now);
        assert_eq!(field.value(), Some("Glam Rock"));
        assert_eq!(field.source(), Some("qobuz"));

        // 4. Manual override beats StreamingService
        field.merge_candidate(Some("Experimental Rock".to_string()), "manual", 1.0, &now);
        assert_eq!(field.value(), Some("Experimental Rock"));
        assert_eq!(field.source(), Some("manual"));

        // 5. Subsequent candidates cannot overwrite Manual
        field.merge_candidate(Some("New Streaming Genre".to_string()), "qobuz", 1.0, &now);
        assert_eq!(field.value(), Some("Experimental Rock"));
        assert_eq!(field.source(), Some("manual"));
    }

    #[test]
    fn test_genre_bpm_key_and_iso_validators() {
        assert!(FieldValidator::is_valid_genre("Art Rock"));
        assert!(FieldValidator::is_valid_genre("Berlin Trilogy"));
        assert!(!FieldValidator::is_valid_genre("Unknown"));
        assert!(!FieldValidator::is_valid_genre("N/A"));
        assert!(!FieldValidator::is_valid_genre("null"));
        assert!(!FieldValidator::is_valid_genre(""));

        assert!(FieldValidator::is_valid_bpm(120));
        assert!(FieldValidator::is_valid_bpm(60));
        assert!(!FieldValidator::is_valid_bpm(0));
        assert!(!FieldValidator::is_valid_bpm(600));

        assert!(FieldValidator::is_valid_key("D"));
        assert!(FieldValidator::is_valid_key("C#m"));
        assert!(!FieldValidator::is_valid_key("Unknown"));
        assert!(!FieldValidator::is_valid_key(""));

        assert!(FieldValidator::is_valid_language("eng"));
        assert!(FieldValidator::is_valid_language("pl"));
        assert!(!FieldValidator::is_valid_language("english"));
        assert!(!FieldValidator::is_valid_language(""));

        assert!(FieldValidator::is_valid_country("GB"));
        assert!(FieldValidator::is_valid_country("USA"));
        assert!(!FieldValidator::is_valid_country("Great Britain"));
        assert!(!FieldValidator::is_valid_country(""));
    }

    #[test]
    fn test_unresolved_fields_remain_not_requested_or_not_found_without_invented_placeholders() {
        let meta = EnrichedMetadata::default();
        assert_eq!(meta.title.value(), None);
        assert_eq!(meta.artist.value(), None);
        assert_eq!(meta.genre.value(), None);
        assert_eq!(meta.bpm.value(), None);
        assert_eq!(meta.isrc.value(), None);
        assert_eq!(meta.barcode.value(), None);
        assert_eq!(meta.musicbrainz_recording_id.value(), None);
    }

    #[test]
    fn test_fuse_genres_splitting_dedup_and_multilingual() {
        let inputs = ["Rock; Pop/Disco", "rock", "Variété française", "Synth-pop/Disco; Pop"];
        let fused = fuse_genres(&inputs);
        // directiva del propietario 2026-08-24: nombres en el cable; anula contrato alpha-2 de S183.
        // S184 genre canonicalization matrix: "Synth-pop"/"Synthpop"/"Synth Pop" fuse to
        // the audited winner "Synth-Pop" (audit frequency 20 vs 8 vs 2).
        assert_eq!(
            fused,
            vec![
                "Rock".to_string(),
                "Pop".to_string(),
                "Disco".to_string(),
                "Variété française".to_string(),
                "Synth-Pop".to_string()
            ]
        );
        assert_eq!(
            format_fused_genres(&inputs).unwrap(),
            "Rock; Pop; Disco; Variété française; Synth-Pop"
        );
    }

    #[test]
    fn test_fuse_languages_precedence_and_majority() {
        // High-prio provider (Qobuz) provides "fra", Spotify provides "eng"
        let inputs = [
            ("English", "spotify", 0.90),
            ("French", "qobuz", 0.85),
            ("fre", "musicbrainz", 0.80),
        ];
        let fused = fuse_languages(&inputs);
        assert_eq!(fused, Some("fra".to_string()));

        // Equal priority majority
        let inputs_majority = [
            ("Spanish", "qobuz", 0.85),
            ("spa", "tidal", 0.90),
            ("English", "deezer", 0.95),
        ];
        let fused_maj = fuse_languages(&inputs_majority);
        assert_eq!(fused_maj, Some("spa".to_string()));
    }

    #[test]
    fn test_fuse_countries_real_names_and_priority() {
        let inputs = [
            ("US", "spotify", 0.80),
            ("GB", "qobuz", 0.90),
            ("United Kingdom", "musicbrainz", 0.85),
        ];
        let fused = fuse_countries(&inputs);
        assert_eq!(fused, Some("United Kingdom".to_string()));
    }

    #[test]
    fn test_fuse_labels_variants() {
        let inputs = ["Sony Music; Columbia", "Sony Music", "Legacy Recordings"];
        let fused = fuse_labels(&inputs);
        assert_eq!(
            fused,
            vec![
                "Sony Music".to_string(),
                "Columbia".to_string(),
                "Legacy Recordings".to_string()
            ]
        );
    }

    #[test]
    fn test_musicbrainz_id_validation_canonical_and_nil() {
        // Legitimate MusicBrainz UUIDs
        assert!(FieldValidator::is_valid_musicbrainz_id("b10bbbfc-cf9e-42e0-be17-e2c3e1d2600d"));
        assert!(FieldValidator::is_valid_musicbrainz_id("8882d694-77a8-4113-8525-f3436e21ea9f"));
        assert!(FieldValidator::is_valid_musicbrainz_id("07b6020a-c539-4d68-aeef-f159f3befc76"));

        // Sentinels and placeholders rejected
        assert!(!FieldValidator::is_valid_musicbrainz_id(""));
        assert!(!FieldValidator::is_valid_musicbrainz_id("   "));
        assert!(!FieldValidator::is_valid_musicbrainz_id("NOT_FOUND"));
        assert!(!FieldValidator::is_valid_musicbrainz_id("not_found"));
        assert!(!FieldValidator::is_valid_musicbrainz_id("null"));
        assert!(!FieldValidator::is_valid_musicbrainz_id("None"));
        assert!(!FieldValidator::is_valid_musicbrainz_id("???"));
        assert!(!FieldValidator::is_valid_musicbrainz_id("N/A"));
        assert!(!FieldValidator::is_valid_musicbrainz_id("0"));
        assert!(!FieldValidator::is_valid_musicbrainz_id("0000"));

        // Malformed UUIDs rejected
        assert!(!FieldValidator::is_valid_musicbrainz_id("b10bbbfc-cf9e-42e0-be17-e2c3e1d2600")); // 35 chars
        assert!(!FieldValidator::is_valid_musicbrainz_id("b10bbbfc-cf9e-42e0-be17-e2c3e1d2600dz")); // invalid hex
        assert!(!FieldValidator::is_valid_musicbrainz_id("b10bbbfc_cf9e_42e0_be17_e2c3e1d2600d")); // underscores instead of dashes

        // Nil UUID rejected
        assert!(!FieldValidator::is_valid_musicbrainz_id("00000000-0000-0000-0000-000000000000"));
    }

    #[test]
    fn test_musicbrainz_synthetic_apocryphal_generation_and_rejection() {
        // Test deterministic calculation matches RFC 4122 / Python uuid5(NAMESPACE_DNS, "artist.musicbrainz.org:Alan Mearns")
        let alan_synth = FieldValidator::compute_synthetic_artist_mbid("Alan Mearns");
        assert_eq!(alan_synth, "e774d650-ebf2-5345-acff-8a5ad5cb0ce9");

        let soft_jazz_synth = FieldValidator::compute_synthetic_artist_mbid("Soft Jazz Playlist");
        assert_eq!(soft_jazz_synth, "bb5aea5e-ebdb-5181-869c-8d67f9a16a54");

        // Verified rejection via synthetic detector
        assert!(FieldValidator::is_synthetic_musicbrainz_id(&alan_synth, Some("Alan Mearns")));
        assert!(FieldValidator::is_synthetic_musicbrainz_id(&alan_synth, None)); // in KNOWN_SYNTHETIC_MBIDS
        assert!(!FieldValidator::is_valid_musicbrainz_id(&alan_synth));
        assert!(!FieldValidator::is_valid_musicbrainz_artist_id(&alan_synth, Some("Alan Mearns")));

        // Rejection when artist name matches synthetic formula even if not in static list
        let custom_artist = "Unknown Synthetic Band 2026";
        let custom_synth = FieldValidator::compute_synthetic_artist_mbid(custom_artist);
        assert!(FieldValidator::is_synthetic_musicbrainz_id(&custom_synth, Some(custom_artist)));
        assert!(!FieldValidator::is_valid_musicbrainz_artist_id(&custom_synth, Some(custom_artist)));

        // Error enum verification
        let err = FieldValidator::validate_musicbrainz_id(&custom_synth, Some(custom_artist)).unwrap_err();
        match err {
            MusicBrainzValidationError::SyntheticApocryphalId(id) => assert_eq!(id, custom_synth),
            other => panic!("Expected SyntheticApocryphalId, got {:?}", other),
        }
    }

    #[test]
    fn test_musicbrainz_known_synthetic_mbids_blacklisted() {
        for &known_synth in KNOWN_SYNTHETIC_MBIDS {
            assert!(
                !FieldValidator::is_valid_musicbrainz_id(known_synth),
                "Known synthetic MBID {} should be rejected by is_valid_musicbrainz_id",
                known_synth
            );
            let err = FieldValidator::validate_musicbrainz_id(known_synth, None).unwrap_err();
            match err {
                MusicBrainzValidationError::SyntheticApocryphalId(id) => assert_eq!(id, known_synth),
                other => panic!("Expected SyntheticApocryphalId, got {:?}", other),
            }
        }
    }
}
